[tool.poetry]
name = "mds-data-engineering"
version = "0.1.0"
description = ""
authors = ["Artem Kindiak <artiomkindiak@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
dagster = "^1.9.13"
dagster-webserver = "^1.9.13"
dagster-dbt = "^0.25.13"
dagster-dlt = "^0.25.13"
dlt = {version = ">=1.6.1", extras = ["filesystem", "sql-database", "parquet", "postgres", "pandas"]}
dagster-postgres = "^0.25.13"
snowflake-sqlalchemy = "^1.7.3"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
ruff = "^0.9.6"
pre-commit = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
